"""
Register combined plantations+rainforests dataset with Detectron2.

13 classes:
  1-7  (PL): Apple, Lemon, Loquat, Mango, Orange, Persimmon, Pomegranate
  8-13 (RF): AliiFig, BangaloPalm, Fern, LeechVine, RubberFig, Umbrella

file_name in the JSON contains absolute image paths so image_root is unused.
"""
import os
from pathlib import Path
from typing import Optional, Union

from detectron2.data import DatasetCatalog, MetadataCatalog
from detectron2.data.datasets.coco import load_coco_json

CLASS_NAMES = [
    "Apple", "Lemon", "Loquat", "Mango", "Orange", "Persimmon", "Pomegranate",
    "AliiFig", "BangaloPalm", "Fern", "LeechVine", "RubberFig", "Umbrella",
]


# Extra per-annotation fields to preserve — same as register_rainforests.py
_EXTRA_ANN_KEYS = ["dbh", "height_ue", "crown_diameter", "depth_mean", "depth_min", "depth_max"]


def _register(name: str, ann_file: Path) -> None:
    if name in MetadataCatalog.list():
        return
    ann_file_str = str(ann_file)
    # Use load_coco_json with extra_annotation_keys so custom fields like
    # 'dbh' survive into the registered dataset dicts.
    # register_coco_instances only keeps COCO defaults and drops 'dbh'.
    DatasetCatalog.register(
        name,
        lambda f=ann_file_str: load_coco_json(
            f, "", name, extra_annotation_keys=_EXTRA_ANN_KEYS
        ),
    )
    MetadataCatalog.get(name).set(
        thing_classes=CLASS_NAMES,
        evaluator_type="coco",
        json_file=ann_file_str,
        image_root="",
    )


def register_all_combined(root: Optional[Union[str, os.PathLike]] = None) -> None:
    if root is None:
        root = os.environ.get(
            "COMBINED_ROOT",
            str(Path(__file__).resolve().parents[1] / "data" / "combined"),
        )
    root = Path(root)
    inst_dir = root / "annotation_inst"

    import re
    for filt_dir in sorted(inst_dir.glob("filtered_rle_f*")):
        if not filt_dir.is_dir():
            continue
        m = re.match(r"filtered_rle_f(\d+)((?:_[A-Za-z0-9]+)*)$", filt_dir.name)
        if not m:
            continue
        fnum = m.group(1)
        suffix = m.group(2) or ""   # e.g. "_repaired" -> combined_inst_rle_f1000_repaired_{split}
        for split in ("train", "val", "test"):
            ann_file = filt_dir / f"instances_{split}.json"
            if ann_file.exists():
                _register(f"combined_inst_rle_f{fnum}{suffix}_{split}", ann_file)

        # Eval subsets: val split into PL-only and RF-only (13 categories kept intact).
        # Generated by scripts/create_combined_eval_subsets.py.
        for domain in ("pl", "rf"):
            ann_file = filt_dir / f"instances_val_{domain}.json"
            if ann_file.exists():
                _register(f"combined_inst_rle_f{fnum}{suffix}_val_{domain}", ann_file)


if __name__ == "__main__":
    register_all_combined()
    print("Classes:", CLASS_NAMES)
    for n in sorted(MetadataCatalog.list()):
        if n.startswith("combined"):
            print(f"Registered: {n}")
