_BASE_: /scratch2/pr65/anur0018/tree_classification/configs/maskdino_FocalNet_L_pl_rle.yaml

DATASETS:
  TRAIN: ("plantations_inst_rle_f1000_train",)
  TEST:  ("plantations_inst_rle_f1000_val",)

INPUT:
  IMAGE_SIZE: 480
  MASK_FORMAT: "bitmask"

SOLVER:
  BASE_LR: 0.0001
  MAX_ITER: 50000
  STEPS: (40000, 47000)
  WARMUP_ITERS: 1000
  CHECKPOINT_PERIOD: 5000

TEST:
  EVAL_PERIOD: 5000
