_BASE_: maskdino_R50_plantations.yaml

DATASETS:
  TRAIN: ("plantations_inst_rle_f1000_train",)
  TEST:  ("plantations_inst_rle_f1000_val",)

INPUT:
  IMAGE_SIZE: 640
  MIN_SCALE: 0.4
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_instance_lsj"

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  MAX_ITER: 50000
  STEPS: (40000, 47000)
  WARMUP_ITERS: 200
  CHECKPOINT_PERIOD: 5000
  AMP:
    ENABLED: True

TEST:
  EVAL_PERIOD: 5000

DATALOADER:
  NUM_WORKERS: 8
  FILTER_EMPTY_ANNOTATIONS: True
