_BASE_: maskdino_R50_pl_rle_f1000_50k.yaml

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  MAX_ITER: 75000
  STEPS: (60000, 70000)
  WARMUP_ITERS: 200
  CHECKPOINT_PERIOD: 5000
  AMP:
    ENABLED: True

TEST:
  EVAL_PERIOD: 5000
